import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/header";
import ProgressBar from "@/components/ui/progress-bar";
import { InitialShow } from "@/components/motion";
import { Toaster } from "react-hot-toast";

import Footer from "@/components/footer";

import Providers from "@/components/providers";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth-options";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions);
  return (
    <>
      <html lang="en">
        <Providers session={session}>
          <body
            className={`${inter.className} min-h-dvh w-full overflow-hidden scrollbar [overflow-y:overlay] [scrollbar-width:none]`}
          >
            <ProgressBar />
            <Header />
            <InitialShow>
              <main>{children}</main>
            </InitialShow>

            <Toaster
              position="top-center"
              toastOptions={{
                className: "!bg-background border border-white/10 !text-primary",
              }}
            />

            <Footer />
          </body>
        </Providers>
      </html>
    </>
  );
}
